name: CI Robot Test - Java Check
on:
	push:
		branches:
			- master
jobs:
	build:
		runs-on:ubuntu-latest

	steps:
	#여기에 로봇의 스케줄을 작성.
		- name:1.코드 체크아웃(작업재료 가져오기)
		uses:actions/checkout@v4

		- name:2.JDK설치
		uses:actions/setup-java@v4
		with:
		distribution:'temurin'
		java-version:'17'

		- name:3.자바코드 컴파일 테스트
		run:
		java -version
		echo "자바환경 설정 완료!"
